copacity/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('copacity_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

copacity_app/urls.py
"""Defines URL patterns for copacity_app."""
from django.urls import path

from . import views

app_name = 'copacity_app'
urlpatterns = [
  # Home Page
  path('', views.index, name='index'),
  # Page that allows you to check in.
  #path('checkIn/', views.checkIn, name='checkIn'),
  # Page the shows all checkIns or all checkIns for any person.
  #path('checkIns/<int:nameId>/', views.checkIns, name='checkIns'),
  # Page to add a new checkIn.
  path('new_checkIn/', views.new_checkIn, name='new_checkIn'),
  # Page to view all your checkIns.
  path('yourCheckIns/', views.yourCheckIns, name = 'yourCheckIns'),
  # Page to view your circles and their checkins.
  path('yourCircles/', views.yourCircles, name = 'yourCircles'),
  # Page to manage circles.
  path('manage_circles/', views.manage_circles, name = 'manage_circles'),
  # Page to add members to a circle.
  path('add_mtm/', views.add_mtm, name = 'add_mtm'),
  # Page to create a circle.
  path('createCircle/', views.createCircle, name = 'createCircle'),
  # Page to select a circle to manage.
  path('manage_circles/', views.manage_circles, name = 'manage_circles'),
  # Page to add or remove members of a circle.
  path('edit_circles/', views.edit_circles, name = 'edit_circles'),
  # Page to view all of a circle's checkins.
  path('circles_checkins/', views.circles_checkins, name = 'circles_checkins'),
  # Page to view all of a circle's checkins from the Your circles page. Added to fix error
  path('circles_checkins_view/', views.circles_checkins_view, name = 'circles_checkins_view'),
  # Page to view all of a circle's checkins from the Your circles page.

  path('circles_checkins_view/<int:circleId>', views.circles_checkins_view, name = 'circles_checkins_view'),
  # Page to view a circle's details from yourCircles page.
  path('circle_details/<int:circleId>', views.circle_details, name = 'circle_details'),
  # Page to perform the update of editted circles.
  path('save_editted_circles/', views.save_editted_circles, name = 'save_editted_circles'),
  # Page to practice the updating a circle.
  path('update_circle/', views.update_circle, name = 'update_circle'),
  # Page to fill in the parameters to request a check-in.
  path('request_checkin/', views.request_checkin, name = 'request_checkin'),
  # Logic to send a SMS to request a check-in.
  path('send_checkin_request/', views.send_checkin_request, name = 'send_checkin_request'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    # Profile update page.
    path('profile/', views.profile, name='profile'),
    # Change password
    path('password-change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done')), name='password_change'),
]

copacity_app/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

class Response(models.Model):
    """A response to the daily check-in. This can be deleted."""
    dateTime = models.DateTimeField(auto_now_add=True)
    yourName = models.IntegerField(blank=False, default=0)
    hardToday = models.CharField(max_length=200)
    goodToday = models.CharField(max_length=200)
    excitedToday = models.CharField(max_length=200)
    suicideRadio = models.IntegerField(blank=False, default=0)
    moodRange = models.IntegerField(blank=False, default=0)
    pintaRange = models.IntegerField(blank=False, default=0)

    def __str__(self):
        """Return a string representation of the model."""
        message = "Person: " + str(self.yourName) + " Mood: " + str(self.moodRange)
        return message



class Circle(models.Model):
    """A Circle"""
    name = models.CharField(max_length=50)
    adminId = models.ForeignKey(User, on_delete=models.CASCADE)
    createdBy = models.CharField(max_length=50)
    createdOn = models.DateTimeField(auto_now_add=True)
    members = models.ManyToManyField(
        User,
        through='CircleMembership',
        through_fields=('circle', 'user'),
        related_name='circle_member',
        blank=True,
        null=True
    )

    def __str__(self):
        """Return a string representation of the model."""
        message = self.name
        return message


class CircleMembership(models.Model):
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    inviter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='circle_invites')

    def __str__(self):
        """Return a string representation of the model."""
        message = str(self.circle) + " member = " + str(self.user)
        return message


class CheckIn(models.Model):
    """A daily checkIn"""
    PEOPLE = [(1, 'Jake'), (2, 'Leah'), (3, 'Raizel'), (4, 'Oscar')]
    SAFE = [(1, 'Yes'), (2, 'No'), (3, 'Maybe')]
    URGENCY = [(1, 'Call now'), (2, 'Text now'), (3, 'Talk later'), (4, 'Not necessary to talk about it'), (5, 'I Prefer not to talk about it')]
#    CIRCLES = [(0, 'none'), (1, 'monopoly'), (2, 'kids')]
    dateTime = models.DateTimeField(auto_now_add=True)
    yourName = models.IntegerField(blank=False, default=0, choices=PEOPLE)
    hardToday = models.CharField(max_length=200)
    goodToday = models.CharField(max_length=200)
    excitedToday = models.CharField(max_length=200)
    thoughts = models.IntegerField(blank=False, default=0, choices=SAFE)
    thoughtsExplained = models.CharField(blank=True, null=True, default='', max_length=400)
    actions = models.IntegerField(blank=False, default=0, choices=SAFE)
    actionsExplained = models.CharField(blank=True, null=True, default='', max_length=400)
    moodRange = models.IntegerField(blank=False, default=5)
    pintaRange = models.IntegerField(blank=False, default=5)
    urgency = models.IntegerField(default=4, choices=URGENCY)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    #visibility = models.IntegerField(blank=False, default=0, choices=CIRCLES)
    visibility = models.ManyToManyField(Circle, related_name='visibility', blank=True, null=True)


    def __str__(self):
        """Return a string representation of the model."""
        name = ""
        if self.yourName == 1:
            name = "Jake"
        if self.yourName == 2:
            name = "Leah"
        if self.yourName == 3:
            name = "Raizel"
        if self.yourName == 4:
            name = "Oscar"

        message = "Name: " + name + ", Good: " + self.goodToday + ", Hard: " + self.hardToday  + ", Mood: " + str(self.moodRange) + ", Urgency: " + str(self.urgency)
        return message

class CircleMembership_Inline(admin.TabularInline):
    model=CircleMembership
    extra=1

class circleAdmin(admin.ModelAdmin):
    inlines = (CircleMembership_Inline,)
    readonly_fields = ('id',)

class usersAdmin(admin.ModelAdmin):
    inlines = (CircleMembership_Inline,)

copacity_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib.auth.views import PasswordChangeDoneView

from django.contrib.auth.models import User
from .models import Response
from .models import CheckIn
from .models import Circle
from .models import CircleMembership
from .forms import CheckInForm
from .forms import CreateCircleForm
from .forms import ManageCirclesForm
from .forms import EditCircleForm
from .forms import SaveCircleForm
from .forms import UpdateCircleForm
from .forms import CheckInRequestForm
from .forms import CheckInSendRequestForm

from twilio.rest import Client

from .credentials import Credentials

import datetime

def index(request):
    """The home page for copacity."""
    return render(request, 'copacity_app/index.html')

@login_required
def new_checkIn(request):
    """Add a new checkIn"""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CheckInForm(request.user)
    else:
        # POST data submitted; process data.
        form = CheckInForm(request.user, data=request.POST)
        if form.is_valid():
            circles = form.cleaned_data['visibility']
            instance = form.save(commit=False)
            instance.yourName = request.user.id
            instance.owner = request.user
            instance.save()
            #instance.visibility.add(firstCircle)
            instance.visibility.set(circles)
            return redirect('copacity_app:index')
        else:
            print("Save failed")
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'copacity_app/new_checkIn.html', context)

@login_required
def yourCheckIns(request):
    """The page to view all of your checkIns."""
    circles = []
    circles = CheckIn.objects.filter(owner=request.user).order_by('-dateTime')

    context = {'circles': circles}
    return render(request, 'copacity_app/your_checkins.html', context)

@login_required
def yourCircles(request):
    """The page for yourCircles that allows you to pick a circle to view check-ins or details."""
    results = CircleMembership.objects.filter(user=request.user)
    circles = []
    for result in results:
        members = result.circle.members.all()
        people = []
        for member in members:
            people.append(member.username)
        circle = {
            'circleId': result.circle.id,
            'name': result.circle.name,
            'adminId': result.circle.adminId,
            'createdBy': result.circle.createdBy,
            'createdOn': result.circle.createdOn,
            'people': people
        }
        circles.append(circle)

    context = {'circles': circles}
    return render(request, 'copacity_app/your_circles_checkins.html', context)

@login_required
def circles_checkins_view(request, circleId):
    """Check-ins that have visibility for the passed circleId."""
    circle = Circle.objects.get(id=circleId)
    circleName = circle.name
    checkIns = circle.visibility.all()
    for checkIn in checkIns:
        checkIn.yourName = User.objects.get(id=checkIn.yourName)

    context = {'checkIns': checkIns, 'circleName': circleName}
    return render (request, 'copacity_app/circles_checkins_view.html', context)

@login_required
def circle_details(request, circleId):
    """Details for the passed circleId."""
    circle = Circle.objects.get(id=circleId)
    members = circle.members.all()
    people = []
    for member in members:
        people.append(member.username)

    context = {'circle': circle, 'people': people}
    return render (request, 'copacity_app/circle_details.html', context)

@login_required
def createCircle(request):
    """Page to create a circle and associate members."""
    if request.method != 'POST':
        form = CreateCircleForm(request.user)
    else:
        form = CreateCircleForm(request.user, data=request.POST)
        if form.is_valid():
            members = form.cleaned_data['members']
            instance = form.save(commit=False)
            instance.adminId = request.user
            instance.createdBy = request.user.id
            ts = datetime.datetime.now()
            instance.createdOn = ts
            instance.save()
            instance.members.set(members, through_defaults={'inviter': request.user})
            return redirect('copacity_app:index')
        else:
            print("Save create circle failed!")

    context = {'form': form}
    return render(request, 'copacity_app/create_circle.html', context)

@login_required
def manage_circles(request):
    """List the circles you belong to in dropdown. Buttons for view checkins or edit circle."""
    if request.method != 'POST':
        form = ManageCirclesForm(request.user)
    else:
        form = ManageCirclesForm(request.user, data=request.POST)
        if form.is_valid():
            circleId = form.cleaned_data['circlesToAdmin']
            circleObj = Circle.objects.get(id=circleId)
            form = UpdateCircleForm(circleId)
            circleInstance = Circle.objects.get(id=circleId)
            context = {'form':form, 'circleInstance':circleInstance}
            return render(request, 'copacity_app/update_circle.html', context)
        else:
            print("There were errors!")

    context = {'form': form}
    return render(request, 'copacity_app/manage_circles.html', context)


@login_required
def circles_checkins(request):
    if request.method != 'POST':
        return redirect('copacity_app:index')
    else:
        form = ManageCirclesForm(request.user, data=request.POST)
        form.is_valid()
        circleName = Circle.objects.filter(id=form.cleaned_data['circlesToAdmin']).values('name')
        circles = CheckIn.objects.filter(id=form.cleaned_data['circlesToAdmin']).order_by('-dateTime')

        context = {'circles': circles, 'circleName':circleName[0]['name']}
        return render(request, 'copacity_app/checkins_admin_view.html', context)


@login_required
def update_circle(request):
    """Update a circle and saving to the DB."""
    if request.method != 'POST':
        form = ManageCirclesForm(request.user, data=request.POST)
        if form.is_valid():
            circleId = form.cleaned_data['circlesToAdmin']
            circleObj = Circle.objects.get(id=circleId)
        form = UpdateCircleForm(circleId)
        circleInstance = Circle.objects.get(id=circleId)
    else:
        form = UpdateCircleSave(data=request.POST)
        if form.is_valid():
            members = form.cleaned_data['members']
            circle = Circle.objects.get(id=form.cleaned_data['id'])
            circle.name = form.cleaned_data["name"]
            circle.createdBy= form.cleaned_data["createdBy"]
            instance = circle.save()
            circle.members.set(members, through_defaults={'inviter': request.user})
            circleInstance = instance
        else:
            return redirect('copacity_app:index')

    context = {'form':form, 'circleInstance':circleInstance}
    return render(request, 'copacity_app/update_circle.html', context)


@login_required
def request_checkin(request):
    """Page to send an SMS to request a checkin."""
    if request.method != 'POST':
        print("Requesting GET check-in!")
    else:
        print("Requesting POST check-in!")
        form = ManageCirclesForm(request.user, data=request.POST)
        print(form) # for some reason if we don't have this, form has no cleaned_data?
        if form.is_valid:
            circleId = form.cleaned_data['circlesToAdmin']
            form = CheckInRequestForm(circleId)
            context = {'form':form}
            return render(request, 'copacity_app/request_checkin.html', context)
        else:
            print("Invalid form, need error handling.")
    return redirect('copacity_app:index')

@login_required
def send_checkin_request(request):
    if request.method != 'POST':
        print("We have and error.")
    else:
        print("In the send post . .. .")
        account_sid = Credentials.account_sid
        auth_token = Credentials.auth_token
        form = CheckInSendRequestForm(data=request.POST)
        if form.is_valid():
            circle_name = form.cleaned_data["circle_name"]
            member_name = form.cleaned_data["name"]
            phoneNumber = form.cleaned_data["phoneNumber"]
            phoneNumber = '+1' + str(phoneNumber)
            print(phoneNumber)
            client = Client(account_sid, auth_token)
            content = "Hi " + member_name + ", " + request.user.username + " wants you to check in to " + circle_name + " at https://co-pacity.herokuapp.com/."
            print(content)
            message = client.messages.create(
                from_='+12056354461',
                body = content,
                to = phoneNumber
            )
            print("Request Sent!")
        else:
            print("Form not valid")
            print(form.errors)
    return redirect('copacity_app:index')





# Are we using this?
@login_required
def edit_circles(request):
    """Add or remove members from a circle."""
    if request.method != 'POST':
        print("Wow! Edit circles works!")
        return redirect('copacity_app:index')
    else:
        form = ManageCirclesForm(request.user, data=request.POST)
        if form.is_valid():
            circleId = form.cleaned_data['circlesToAdmin']
            circleObj = Circle.objects.get(id=circleId)
        form = EditCircleForm(circleId)
        context = {'form':form}
        return render(request, 'copacity_app/edit_circles.html', context)

# Are we using this?
# This doesn't seem to be updating the database.
@login_required
def save_editted_circles(request):
    """To update the database with editted circles."""
    print(request.method)
    if request.method != 'POST':
        print("Wow! Save editted circles works!")
        return redirect('copacity_app:index')

    else:

copacity_app/templates/copacity_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--    <link rel="stylesheet" href="starter-template.css"> -->
    <title>Co-pacity</title>
  </head>
  <body>
  </br>
  </br>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'copacity_app:index' %}">Co-pacity<span class="sr-only">(current)</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#">Hello, {{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'copacity_app:new_checkIn' %}">Check-In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'copacity_app:yourCheckIns' %}">Your Check-Ins</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'copacity_app:yourCircles' %}">Your Circles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'copacity_app:createCircle' %}">Create a Circle</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'copacity_app:manage_circles' %}">Manage Circles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:password_change' %}">Change Password</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>

        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'password_reset' %}">Reset Password</a>
          </li>

        {% endif %}
      </ul>
    </div>
  </nav>

<main role="main" class="container">

{% block content %}{% endblock content %}

</main><!-- /.container -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

copacity_app/templates/copacity_app/circles_checkins_view.html
{% extends "copacity_app/base.html" %}

{% block content %}

  <div>
    </br>
    </br>
    <a class="btn btn-primary" href="{% url 'copacity_app:yourCircles' %}" role="button">BACK TO YOUR CIRCLES</a>
    <a class="btn btn-primary" href="{% url 'copacity_app:new_checkIn' %}" role="button">CHECK-IN<a/>
    <h1>Check-Ins for Circle</h1>
    <p class="lead">Here are the Check-Ins for {{ circleName }}. </p>
    <ul>
      {% for checkIn in checkIns %}
        <p>Check in: {{ checkIn.id}}</p>
        <p>{{ checkIn.yourName}} checked in on {{checkIn.dateTime}} </p>
        <p> Hard Today: {{ checkIn.hardToday }}</p>
        <p> Good Today: {{ checkIn.goodToday }}</p>
        <p> Excited Today: {{ checkIn.excitedToday }}</p>
        <p> Safe Thoughts: {{ checkIn.thoughts}} &nbsp &nbsp &nbsp Explanation: {{ checkIn.thoughtsExplained }}</p>
        <p> Safe Actions: {{ checkIn.actions}} &nbsp &nbsp &nbsp Explanation: {{ checkIn.actionsExplained }}</p>
        <p> Mood: {{ checkIn.moodRange }} &nbsp &nbsp &nbsp Pinta Picture: {{ checkIn.pintaRange }}</p>
        <p> Urgency: {{ checkIn.urgency}}</p>
        </br>
        </br>
      {% empty %}
        <li>No one has checked in.</li>
      {% endfor %}
    </ul>
  </div>

{% endblock content %}

copacity_app/templates/copacity_app/create_circle.html
{% extends "copacity_app/base.html" %}

{% block content %}

  <form action="{% url 'copacity_app:createCircle' %}" method='POST'>
    {% csrf_token %}
      <div class="form-group row mb-0">
        <div class="form-group row mb-0">
        <h1>Create Circle</h1>
          <p class="col-sm-12">Hi <strong>{{user.username}}</strong>, create a new circle:</p>
        </div>
      </div>
      <div class="form-group row">
        <label for="name" class="col-sm-4 col-form-label">Circle Name:</label>
        {{ form.name }}
      </div>
      <div class="form-group row">
        <label for="members" class="col-sm-4 col-form-label">Add members:</label>
        {{ form.members }}
      </div>
      <input type="submit" class="btn-block btn-primary" value="CREATE CIRCLE">
      <input type="submit" class="btn-block btn-primary" value="CANCEL" formaction="{% url 'copacity_app:index' %}" formnovalidate>
    </form>


{% endblock content %}

copacity_app/templates/copacity_app/edit_circles.html
{% extends "copacity_app/base.html" %}

{% block content %}

  <div>
    </br>
    <div class="form-group row">
      <form action="{% url 'copacity_app:manage_circles' %}" method='GET'>
        {% csrf_token %}
        <input type="submit" class="btn-block btn-primary" value="BACK TO ADMIN CIRCLES">
      </form>
    </div>
    </br>
    </br>
    <h1>Your Circles</h1>
    <p class="lead">Edit your circles. </p>
    <form action="{% url 'copacity_app:save_editted_circles' %}" method='POST'>
      {% csrf_token %}
        <div class="form-group row mb-0">
          <div class="form-group row mb-0">
            <p class="col-sm-12">Hi <strong>{{user.username}}</strong>, edit your circle here.</p>
          </div>
        </div>
        <div class="form-group row">
          <label for="name" class="col-sm-4 col-form-label">Circle Id:</label>
          {{ form.id }}
        </div>

        <div class="form-group row">
          <label for="name" class="col-sm-4 col-form-label">Circle Name:</label>
          {{ form.name }}
        </div>
        <div class="form-group row">
          <label for="name" class="col-sm-4 col-form-label">Created By:</label>
          {{ form.createdBy }}
        </div>
        <div class="input-group">
          <label for="members" class="col-sm-4 col-form-label">Add members:</label>
          <div class="form-check">
            {{ form.members }}
          </div>
        </div>
        <div class="form-group row">
          <input type="submit" class="btn-block btn-primary" value="SUBMIT" formaction="{% url 'copacity_app:save_editted_circles' %}">
          <input type="submit" class="btn-block btn-primary" value="CANCEL" formaction="{% url 'copacity_app:index' %}" formnovalidate>
        </div>
      </form>
  </div>

{% endblock content %}

copacity_app/templates/copacity_app/index.html
{% extends "copacity_app/base.html" %}

{% block content %}

    <div class="starter-template">
      <h1>Co-pacity</h1>
      <p class="lead">Coping together</p>
    </div>
    <a href="{% url 'copacity_app:new_checkIn' %}"><button type="button" class="btn btn-primary btn-lg">Check In</button><a/>
<!--
    <button type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      View recent checkins for . . .
    </button>
-->
{% endblock content %}

copacity_app/templates/copacity_app/manage_circles.html
{% extends "copacity_app/base.html" %}

{% block content %}

<form action="{% url 'copacity_app:manage_circles' %}" method='POST'>
  {% csrf_token %}
    <div class="form-group row mb-0">
      <div class="form-group row mb-0">
        <p class="col-sm-12">Hi, select a circle to administer.</p>
      </div>
    </div>
    <div class="form-group row">
      <label for="name" class="col-sm-4 col-form-label">Your circles:</label>
      {{ form.circlesToAdmin }}
    </div>
    <input type="submit" class="btn-block btn-primary" formaction="{% url 'copacity_app:circles_checkins' %}"value="VIEW ALL CHECKINS FOR THIS CIRCLE">
    <input type="submit" class="btn-block btn-primary" formaction="{% url 'copacity_app:manage_circles' %}" value="EDIT CIRCLE">
    <input type="submit" class="btn-block btn-primary" formaction="{% url 'copacity_app:request_checkin' %}" value="REQUEST CHECK-IN">
    <input type="submit" class="btn-block btn-primary" value="CANCEL" formaction="{% url 'copacity_app:index' %}" formnovalidate>
  </form>

{% endblock content %}

copacity_app/templates/copacity_app/request_checkin.html
{% extends "copacity_app/base.html" %}

{% block content %}

<form action="{% url 'copacity_app:send_checkin_request' %}" method='POST'>
  {% csrf_token %}
    <div class="form-group row mb-0">
      <div class="form-group row mb-0">
        <p class="col-sm-12">Hi, Request a check-in.</p>
      </div>
    </div>
    <div class="form-group row">
      {{form.circle_name.errors}}
            <label for="id_name" class="col-sm-4 col-form-label">Circle Name:</label>
      {{form.circle_name}}
    </div>
    <div class="form-group row">
      {{form.name.errors}}
            <label for="id_name" class="col-sm-4 col-form-label">Member's Name:</label>
      {{form.name}}
    </div>
    <div class="form-group row">
      {{form.phoneNumber.errors}}
      <label for="phoneNumber" class="col-sm-4 col-form-label">Phone number:</label>
      {{form.phoneNumber}}
    </div>
    <input type="submit" class="btn-block btn-primary" value="SEND REQUEST">
    <input type="submit" class="btn-block btn-primary" value="CANCEL" formaction="{% url 'copacity_app:index' %}" formnovalidate>
  </form>

{% endblock content %}

copacity_app/templates/copacity_app/your_checkins_depracated.html
{% extends "copacity_app/base.html" %}

{% block content %}

  <div>
    </br>
    <a class="btn btn-primary" href="/" role="button">HOME</a>
    <a href="{% url 'copacity_app:new_checkIn' %}"><button type="button" class="btn btn-primary">CHECK-IN</button><a/>
    <h1>Your Check-Ins</h1>
    <p class="lead">Here are your Check-Ins, {{user.username}}: </p>
    <ul>
      {% for circle in circles %}
        <p>Check in: {{ circle.id}}</p>
        <p>{{ request.user.username}} checked in on {{circle.dateTime}} </p>
        <p> Hard Today: {{ circle.hardToday }}</p>
        <p> Good Today: {{ circle.goodToday }}</p>
        <p> Excited Today: {{ circle.excitedToday }}</p>
        <p> Safe Thoughts: {{ circle.thoughts}} &nbsp &nbsp &nbsp Explanation: {{ circle.thoughtsExplained }}</p>
        <p> Safe Actions: {{ circle.actions}} &nbsp &nbsp &nbsp Explanation: {{ circle.actionsExplained }}</p>
        <p> Mood: {{ circle.moodRange }} &nbsp &nbsp &nbsp Pinta Picture: {{ circle.pintaRange }}</p>
        <p> Urgency: {{ circle.urgency}}</p>
        </br>
        </br>
      {% empty %}
        <li>You checked in.</li>
      {% endfor %}
    </ul>
  </div>

{% endblock content %}